MESSAGE(NEW_GAME_EASY,
	"New game (Easy)",
	"Новая игра (Лёгкая)",
	"Neues Spiel (Einfach)")

MESSAGE(NEW_GAME_DIFFICULT,
	"New game (Difficult)",
	"Новая игра (Тяжёлая)",
	"Neues Spiel (Schwierig)")

MESSAGE(NEW_GAME_FOUR_BRIDGES,
	"New game (Four Bridges)",
	"Новая игра (Четыре моста)",
	"Neues Spiel (Vier Brücken)")

MESSAGE(NEW_GAME_CUSTOM,
	"New game (Custom)",
	"Новая игра (Личный)",
	"Neues Spiel (Eigene)")

MESSAGE(LOAD,
	"Load game",
	"Загрузить игру",
	"Spiel laden")

MESSAGE(BACK,
	"Back",
	"Назад",
	"Zurück")

MESSAGE(LOADING_FAILED,
	"Couldn't load map",
	"Не удалось загрузить карту",
	"Laden der Karte fehlgeschlagen")

MESSAGE(EXIT,
	"Exit",
	"Выход",
	"Beenden")

MESSAGE(CHANGE_ORIENTATION,
	"Change screen orientation",
	"Сменить ориентацию экрана",
	"Bildschirm drehen")

MESSAGE(CONTINUE,
	"Continue",
	"Продолжить",
	"Spiel fortsetzen")

MESSAGE(HINT,
	"Hint",
	"Подсказать",
	"Hinweis")

MESSAGE(UNDO,
	"Undo",
	"Отменить ход",
	"Zug zurücknehmen")

MESSAGE(TOGGLE_LANGUAGE,
	"Русский",
	"Deutsch",
	"English")

MESSAGE( WIN,
	"Solitaire is solved. Congratulations!",
	"Пасьянс решён. Поздравляем!",
	"Glückwunsch, das Spiel ist gelöst!" )

MESSAGE( LOSE,
	"There is no more free pair. You lose.",
	"Свободных пар больше нет. Вы проиграли.",
	"Keine freien Paare mehr, du verlierst." )

MESSAGE(MOVES_LEFT,
	"Available pairs: %d",
	"Доступно пар: %d",
	"Verfügbare Paare: %d")

MESSAGE(HELP,
	"Menu : game menu",
	"Menu : меню игры",
	"Menu : Spielmenü anzeigen")
